name:                gabble
version:             0.1.0.0
github:              "https://github.com/aneksteind/gabble"
license:             BSD3
author:              "David Anekstein"
maintainer:          "example@example.com"
copyright:           "2019 David Anekstein"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/aneksteind/gabble#readme>

dependencies:
- base >= 4.7 && < 5
- random
- mtl >= 2.2.2
- monad-extras >= 0.6.0
- mersenne-random-pure64
- mwc-random >= 0.14.0.0
- primitive >= 0.6.4.0
- heap >= 1.0.4
- text
- data-fix >= 0.2.0
- recursion-schemes >= 5.1.3
- recursion-schemes-ext >= 1.0.0.4
- data-ordlist >= 0.4.7.0
- vector >= 0.12.0.3
- vector-algorithms >= 0.8.0.1

library:
  source-dirs: src
  default-extensions: OverloadedStrings

executables:
  gabble-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -Wall
    - -with-rtsopts=-N
    dependencies:
    - gabble

tests:
  gabble-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gabble
